name: Reentrenar Euromillones

on:
  schedule:
    - cron: '0 3 * * 6'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Descargar sorteos
        run: |
          python main.py

      - name: Reentrenar modelos
        run: |
          python AutoTrain.py

      - name: Crear tag
        run: echo "TAG=models-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Crear release y subir PKL
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          generate_release_notes: true
          files: |
            artifacts/*.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    

